---
book_repo: cloudfoundry/docs-book-cloudfoundry
cred_repo: pivotal-cf/docs-oss-site-credentials

sections:
- repository:
    name: cloudfoundry/docs-cloudfoundry-concepts
  directory: concepts
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-dev-guide
  directory: devguide
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-cf-admin
  directory: adminguide
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-services
  directory: services
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-deploying-cf
  directory: deploying
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-bosh
  directory: bosh
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-running-cf
  directory: running
  subnav_template: cf-subnav.erb
- repository:
    name: cloudfoundry/docs-buildpacks
  directory: buildpacks
  subnav_template: cf-subnav.erb

template_variables:
  support_url: http://www.cloudfoundry.org/get-in/index.html
  title_image: ../images/logo_org.png
  title: Documentation
  hero_text: Detailed documentation to help you deploy, scale, and troubleshoot applications on Cloud Foundry.
  app_domain: example.com
  book_title: Cloud Foundry Documentation
  quota_resource: quota space
  external_ips: external IP addresses
  admin: your Cloud Foundry administrator
  api_endpoint: <a href="http://docs.cloudfoundry.org/running/cf-api-endpoint.html">the URL of the Cloud Controller in your Cloud Foundry instance</a>
  console_2: If you have a Cloud Foundry account, refer to the <a href="http://docs.cloudfoundry.org/running/cf-api-endpoint.html">Indentifying the API Endpoint for your Cloud Foundry Instance</a> topic to determine the URL of the Cloud Controller in your Cloud Foundry instance. Click <strong>Manage Cloud...</strong> to add this URL to your Cloud Foundry account. Validate the account and continue through the wizard.</a>
  info_loc: In your Cloud Foundry deployment manifest
  uaa_cred: refer to the the <code>uaa scim</code> section
  GSG_intro_sentence:
  product_full: Cloud Foundry
  product_short: Cloud Foundry
  known_issues: <a href="http://docs.cloudfoundry.org/running/troubleshooting.html">Troubleshooting Cloud Foundry</a>
  dev_console_note:
  dev_console_1:
  dev_console_2: CLI
  dev_console_3:
  dev_console_4:
  dev_console_5:
  gen_GSG:
  cli_v6: <a href="http://docs.cloudfoundry.org/devguide/installcf/whats-new-v6.html">Getting Started with cf CLI v6</a>
  pools_link: <a href="http://www.google.com/url?q=http%3A%2F%2Fdocs.cloudfoundry.org%2Fbosh%2Fdeployment-basics.html%23resource-pools&sa=D&sntz=1&usg=AFQjCNEyabXy-ymhPvBarCYQP8ZfIeL7pA">resource pools</a>
  om_resurrector_header:
  om_resurrector_text:
  max_in_flight: your max\_in\_flight number of DEAs
  az: availability zones
  pcf_rec: Cloud Foundry
  console_links:
  app_sec_groups: <a href="http://docs.cloudfoundry.org/adminguide/app-sec-groups.html">Application Security Groups</a>
  dea_properties: <a href="http://bosh.io/jobs/dea_next?source=github.com/cloudfoundry/cf-release&version=197">DEA Network Properties</a>
  net_traffic_rules: <a href="http://docs.cloudfoundry.org/adminguide/app-sec-groups.html">network traffic rules</a>
  port_limitations: <span>Applications running on Cloud Foundry receive requests through the URLs configured for the application. HTTP requests arrive on ports 80 and 443. Additionally, Cloud Foundry requires a channel for TCP/WebSocket traffic.<br><br>Some production load balancers require separate ports for HTTP and TCP/WebSocket traffic. HAProxy allows both kinds of traffic on the same port. However, HAProxy is suitable for only lab and test environments. Applications deployed with the default settings of <code>cf-release</code> use port 4443 for TCP/WebSocket communications. To assign TCP/WebSocket traffic to a different port, you must make the following changes:<ul><li> Set the value of the <code>port</code> sub-key of the <code>logger\_endpoint</code> key in your manifest.</li><li> Configure your HAProxy or load balancer to receive TCP traffic on the port you specified. This configuration enables you to access logs from your app with the <code>cf logs APP_NAME</code> command.</li></ul> Note that if you remove the <code>port</code> sub-key from your manifest, you must configure port 443 for TCP/WebSocket traffic in your load balancer or HAProxy.</span>
  domains_shared_domains:
  ssl:
  disable_custom_buildpacks:
public_host: docs.cloudfoundry.org
